language: java
jdk:
 - oraclejdk8

script:
 - chmod +x ./gradlew build connectedCheck
 
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEYID
  secret_access_key: $SECRET_ACCESSKEY
  skip_cleanup: true
  region: "us-east-1"  
  app: "qualibrate-api"
  env: "qualibrate-api-qa"
  bucket_name: "elasticbeanstalk-us-east-1-363177061610"
  zip_file: 'build/libs/qualibrate-api-challange-1.0.0.jar'
  on:
    branch: master

after_deploy:  "echo 'Application Deployed to Cloud'"
  