language: java
jdk:
 - oraclejdk8
before_install:
 - chmod +x gradlew
before_script:
 - chmod +x ./gradlew
script:
 - chmod +x ./gradlew
 
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEYID
  secret_access_key: $SECRET_ACCESSKEY
  skip_cleanup: true
  region: "us-east-1"  
  app: "qualibrate-api-qa"
  env: "qa"
  bucket_name: "qualibrate-api-qa-ebs-us-east-1-363177061610"
  zip_file: 'build/libs/qualibrate-api-challange-1.0.0.jar'
  on:
    branch: master

after_deploy:  "echo 'Application Deployed to Cloud'"