language: java
jdk:
 - oraclejdk8
before_install:
 - chmod +x gradlew
before_script:
 - chmod +x ./gradlew
script:
 - chmod +x ./gradlew
 
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEYID
  secret_access_key: $SECRET_ACCESSKEY
  skip_cleanup: true
  region: ap-south-1  
  app: qualibrate-api-qa
  env: qualibrate-api-qa
  bucket_name: "elasticbeanstalk-ap-south-1-363177061610"
  zip_file: 'build/distributions/qualibrate-api-challange-1.0.0-beanstalk.zip'
  on:
    branch: master

after_deploy:  "echo 'Application Deployed to Cloud'"